unifiedUpgradeAllowed: true
databaseUpgradeReady: true
xray:
  jfrogUrl: http://xray-xray.rt:8082
replicaCount: 1
postgresql:
  postgresqlPassword: xray
rabbitmq-ha:
  enabled: false
rabbitmq:
  enabled: true
  auth:
    username: guest
    password: guest
common:
  customInitContainersBegin: |
    - name: "download-fluentd-conf-on-persistent-volume"
      image: "{{ .Values.initContainerImage }}"
      imagePullPolicy: "{{ .Values.imagePullPolicy }}"
      command:
        - 'sh'
        - '-c'
        - >
          mkdir -p {{ .Values.xray.persistence.mountPath }}/etc/fluentd/;
          wget https://raw.githubusercontent.com/jfrog/log-analytics-datadog/master/fluent.conf.xray -O {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf
      volumeMounts:
        - mountPath: "{{ .Values.xray.persistence.mountPath }}"
          name: data-volume
    - name: "prepare-fluentd-conf-on-persistent-volume"
      image: "{{ .Values.initContainerImage }}"
      imagePullPolicy: "{{ .Values.imagePullPolicy }}"
      command:
        - 'sh'
        - '-c'
        - >
          sed 's/API_KEY/{{ .Values.datadog.api_key }}/' {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf > {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf.new;
          mv {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf.new {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf;
      volumeMounts:
        - mountPath: "{{ .Values.xray.persistence.mountPath }}"
          name: data-volume
  customSidecarContainers: |
    - name: "xray-fluentd-sidecar"
      image: "releases-docker.jfrog.io/reg2/fluentd-1.12.0"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - mountPath: "{{ .Values.xray.persistence.mountPath }}"
          name: data-volume
      env:
        - name: JF_PRODUCT_DATA_INTERNAL
          value: {{ .Values.xray.persistence.mountPath }}
        - name: FLUENTD_CONF
          value: ../../../../{{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf
datadog:
  api_key: datadog_api_key