unifiedUpgradeAllowed: true
databaseUpgradeReady: true
postgresql:
  postgresqlPassword: xray
rabbitmq-ha:
  enabled: false
rabbitmq:
  enabled: true
  auth:
    username: guest
    password: guest
datadog:
  apiKey: datadog_api_key
jfrog:
  siem:
    accessToken: jfrog_access_token
    jpdUrl: jpd_url
common:
  customInitContainersBegin: |
    - name: "download-fluentd-conf-on-persistent-volume"
      image: "{{ .Values.initContainerImage }}"
      imagePullPolicy: "{{ .Values.imagePullPolicy }}"
      command:
        - 'sh'
        - '-c'
        - >
          mkdir -p {{ .Values.xray.persistence.mountPath }}/etc/fluentd/;
          wget https://raw.githubusercontent.com/jfrog/log-analytics-datadog/3b8ceef704569538939f6010fc3fbab215976442/fluent.conf.xray -O {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf
      volumeMounts:
        - mountPath: "{{ .Values.xray.persistence.mountPath }}"
          name: data-volume
    - name: "prepare-fluentd-conf-on-persistent-volume"
      image: "{{ .Values.initContainerImage }}"
      imagePullPolicy: "{{ .Values.imagePullPolicy }}"
      command:
        - 'sh'
        - '-c'
        - >
          sed 's/API_KEY/{{ .Values.datadog.apiKey }}/' {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf > {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf.new;
          mv {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf.new {{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf;
          sed 's/ACCESS_TOKEN/{{ .Values.jfrog.siem.accessToken }}/' {{ .Values.xray.persistence.mountPath }}/etc/fluentd/siemfluentd.conf > {{ .Values.xray.persistence.mountPath }}/etc/fluentd/siemfluentd.conf.new;
          mv {{ .Values.xray.persistence.mountPath }}/etc/fluentd/siemfluentd.conf.new {{ .Values.xray.persistence.mountPath }}/etc/fluentd/siemfluentd.conf;
          sed 's/JPD_URL/{{ .Values.jfrog.siem.jpdUrl }}/' {{ .Values.xray.persistence.mountPath }}/etc/fluentd/siemfluentd.conf > {{ .Values.xray.persistence.mountPath }}/etc/fluentd/siemfluentd.conf.new;
          mv {{ .Values.xray.persistence.mountPath }}/etc/fluentd/siemfluentd.conf.new {{ .Values.xray.persistence.mountPath }}/etc/fluentd/siemfluentd.conf;
      volumeMounts:
        - mountPath: "{{ .Values.xray.persistence.mountPath }}"
          name: data-volume
  customSidecarContainers: |
    - name: "xray-platform-fluentd-sidecar"
      image: "releases-docker.jfrog.io/reg2/fluentd:1.12.3"
      imagePullPolicy: "IfNotPresent"
      volumeMounts:
        - mountPath: "{{ .Values.xray.persistence.mountPath }}"
          name: data-volume
      env:
        - name: JF_PRODUCT_DATA_INTERNAL
          value: {{ .Values.xray.persistence.mountPath }}
        - name: FLUENTD_CONF
          value: ../../../../{{ .Values.xray.persistence.mountPath }}/etc/fluentd/fluentd.conf
